// TORFL (ТРКИ) validation track. The official exam has exactly 6 CEFR levels (A1→C2), grouped
// into 3 bands (A/B/C). There are NO official sub-levels (A1.1 etc. are only language-school
// course units), so we stick to the 6 real levels. Progress is validated step by step through
// the 6 épreuves of each level. v1 covers production (écrit/oral) + comprehension (écrite/orale)
// + translation (ru↔fr), all graded by an LLM (see lib/mistral). Pure data + helpers (no deps).

export type Cefr = "A1" | "A2" | "B1" | "B2" | "C1" | "C2";
export type Band = "A" | "B" | "C";

export const BAND_META: Record<Band, { title: string; blurb: string }> = {
  A: { title: "A · Utilisateur élémentaire", blurb: "Bases : se présenter, besoins simples." },
  B: { title: "B · Utilisateur indépendant", blurb: "Autonomie : argumenter, échanger librement." },
  C: { title: "C · Utilisateur expérimenté", blurb: "Maîtrise : discours élaboré, niveau natif." },
};

export const BAND_ORDER: Band[] = ["A", "B", "C"];

// The 5 official ТРКИ/TORFL subtests.
export type Skill =
  | "grammaire" // Лексика-Грамматика — QCM lexique/grammaire
  | "lecture" // Чтение — compréhension écrite (texte ru + questions)
  | "ecoute" // Аудирование — compréhension orale (texte ru lu à voix haute + questions)
  | "ecrit" // Письмо — expression écrite
  | "oral"; // Говорение — expression orale

export interface ProductionTask {
  id: string; // e.g. "A1-ecrit"
  cefr: Cefr;
  skill: Skill;
  titleFr: string;
  promptFr: string; // instruction in French; the response is in Russian (production)
  minWords?: number;
  generated?: boolean; // true = content (text/questions/QCM) is generated by the LLM
}

export interface McqQuestion {
  question: string; // in Russian (a sentence with a gap or a grammar choice)
  options: string[]; // candidate answers
}

/** An exam item generated on demand for the generated subtests. */
export interface ExamItem {
  passage?: string; // lecture / ecoute: a Russian text
  questions?: string[]; // lecture / ecoute: questions in French
  mcq?: McqQuestion[]; // grammaire: multiple-choice questions
  token?: string; // grammaire: server-side key to the correct answers (never the answers themselves)
}

export interface Level {
  cefr: Cefr;
  band: Band;
  title: string; // official designation
  subtitle: string;
  theme: string; // short theme hint used when generating items
  tasks: ProductionTask[];
}

// Build the 6 épreuves of a level: two authored production tasks (écrit + oral) plus four
// generated tasks (compréhension écrite/orale, traduction ru→fr / fr→ru).
function tasks(
  cefr: Cefr,
  ecrit: { titleFr: string; promptFr: string; minWords: number },
  oral: { titleFr: string; promptFr: string },
): ProductionTask[] {
  // Official ТРКИ order: Лексика-Грамматика, Чтение, Аудирование, Письмо, Говорение.
  return [
    {
      id: `${cefr}-grammaire`,
      cefr,
      skill: "grammaire",
      generated: true,
      titleFr: "Lexique-grammaire",
      promptFr: "Choisis la bonne réponse pour chaque question (QCM).",
    },
    {
      id: `${cefr}-lecture`,
      cefr,
      skill: "lecture",
      generated: true,
      titleFr: "Compréhension écrite",
      promptFr: "Lis le texte russe, puis réponds aux questions en français.",
    },
    {
      id: `${cefr}-ecoute`,
      cefr,
      skill: "ecoute",
      generated: true,
      titleFr: "Compréhension orale",
      promptFr: "Écoute le texte russe (bouton ▶), puis réponds aux questions en français.",
    },
    { id: `${cefr}-ecrit`, cefr, skill: "ecrit", ...ecrit },
    { id: `${cefr}-oral`, cefr, skill: "oral", ...oral },
  ];
}

export const TORFL: Level[] = [
  {
    cefr: "A1",
    band: "A",
    title: "A1 · Élémentaire (ТЭУ)",
    subtitle: "Se présenter et gérer des besoins très simples.",
    theme: "vie quotidienne, se présenter, famille",
    tasks: tasks(
      "A1",
      {
        titleFr: "Se présenter",
        promptFr:
          "Écris 4 à 5 phrases simples pour te présenter : prénom, âge, pays où tu habites, ce que tu fais, ta famille.",
        minWords: 20,
      },
      {
        titleFr: "Présentation orale",
        promptFr: "Présente-toi à l’oral : bonjour, ton prénom, d’où tu viens, ce que tu fais.",
      },
    ),
  },
  {
    cefr: "A2",
    band: "A",
    title: "A2 · Basique (ТБУ)",
    subtitle: "Échanges courants sur des sujets familiers.",
    theme: "quotidien, passé et futur proches, loisirs",
    tasks: tasks(
      "A2",
      {
        titleFr: "Ma journée",
        promptFr:
          "Raconte par écrit ta journée d’hier et tes projets pour demain (6–8 phrases, passé et futur).",
        minWords: 40,
      },
      {
        titleFr: "Mon week-end",
        promptFr: "Raconte à l’oral ton dernier week-end et ce que tu vas faire le prochain.",
      },
    ),
  },
  {
    cefr: "B1",
    band: "B",
    title: "B1 · ТРКИ-1",
    subtitle: "Autonomie sur la plupart des situations courantes.",
    theme: "opinions, situations courantes, récits",
    tasks: tasks(
      "B1",
      {
        titleFr: "Lettre & opinion",
        promptFr:
          "Rédige une lettre informelle (~90 mots) à un ami : invite-le à un événement et donne ton opinion sur un sujet, avec au moins deux arguments.",
        minWords: 80,
      },
      {
        titleFr: "Donner son avis",
        promptFr: "Donne ton avis à l’oral sur la vie en ville et justifie-le avec des exemples.",
      },
    ),
  },
  {
    cefr: "B2",
    band: "B",
    title: "B2 · ТРКИ-2",
    subtitle: "Aisance et argumentation sur des sujets variés.",
    theme: "société, technologie, travail, argumentation",
    tasks: tasks(
      "B2",
      {
        titleFr: "Texte argumenté",
        promptFr:
          "Rédige un texte argumenté (~150 mots) sur les avantages et limites du télétravail : introduction, arguments, conclusion.",
        minWords: 130,
      },
      {
        titleFr: "Exposé structuré",
        promptFr:
          "Présente à l’oral, de façon structurée, les avantages et inconvénients de vivre en ville plutôt qu’à la campagne.",
      },
    ),
  },
  {
    cefr: "C1",
    band: "C",
    title: "C1 · ТРКИ-3",
    subtitle: "Maîtrise opérationnelle, discours élaboré.",
    theme: "thèmes abstraits, culture, enjeux de société",
    tasks: tasks(
      "C1",
      {
        titleFr: "Essai",
        promptFr:
          "Rédige un essai (~250 mots) sur le rôle de la culture dans la société, avec une thèse claire, des arguments et des exemples.",
        minWords: 220,
      },
      {
        titleFr: "Exposé argumenté",
        promptFr:
          "Développe oralement une position argumentée et nuancée sur un enjeu de société complexe.",
      },
    ),
  },
  {
    cefr: "C2",
    band: "C",
    title: "C2 · ТРКИ-4",
    subtitle: "Niveau quasi natif, registre soutenu.",
    theme: "sujets abstraits, registre soutenu, philosophie",
    tasks: tasks(
      "C2",
      {
        titleFr: "Texte expert",
        promptFr:
          "Rédige un texte de niveau quasi natif (~300 mots) analysant un thème abstrait (le temps, la mémoire, la liberté…), style soutenu.",
        minWords: 270,
      },
      {
        titleFr: "Plaidoyer nuancé",
        promptFr:
          "Construis oralement un plaidoyer convaincant et nuancé sur une question abstraite, registre soutenu.",
      },
    ),
  },
];

export const LEVELS: Level[] = TORFL;
export const ALL_TASKS: ProductionTask[] = TORFL.flatMap((l) => l.tasks);

export function findLevel(cefr: string): Level | undefined {
  return TORFL.find((l) => l.cefr === cefr);
}

export function findTask(id: string): ProductionTask | undefined {
  return ALL_TASKS.find((t) => t.id === id);
}

/** A level is validated when all its 6 épreuves have been passed. */
export function levelValidated(level: Level, passed: Set<string>): boolean {
  return level.tasks.every((t) => passed.has(t.id));
}

/** Target description for the LLM (the official level — no sub-levels). */
export function targetDescription(task: ProductionTask): string {
  return `${task.cefr}`;
}

export const SKILL_LABEL: Record<Skill, string> = {
  grammaire: "Lexique-grammaire",
  lecture: "Compréhension écrite",
  ecoute: "Compréhension orale",
  ecrit: "Expression écrite",
  oral: "Expression orale",
};

// ---- Grading result (shared with the client UI) ----
export interface GradeCriterion {
  name: string;
  score: number; // 0–5
  comment: string;
}
export interface GradeResult {
  score: number; // 0–100
  pass: boolean;
  feedback: string; // overall feedback in French
  criteria: GradeCriterion[];
  corrected?: string; // a corrected version of the response (optional)
}

export const PASS_SCORE = 70;
